modules/
   __init__.py
   cmyk/
       __init__.py
       analyzer.py
       cache_engine.py
       context.py
       cost_engine.py
       history.py
       inventory_engine.py
       page_size.py
       pdf_utils.py
